{
 "title": "NETCAP",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "queryInterval",
    "query": "1m,5m,10m,30m,1h,3h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "host", "query": "label_values(host)" },
   { "name": "instance", "query": "label_values(instance)" },
   { "name": "quantile", "query": "0.1,0.5,0.8,0.9,0.99" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "content": "\n                           \n                           / |\n     _______    ______   _10 |_     _______   ______    ______\n    /     / \\  /    / \\ / 01/  |   /     / | /    / \\  /    / \\\n    0010100 /|/011010 /|101010/   /0101010/  001010  |/100110  |\n    01 |  00 |00    00 |  10 | __ 00 |       /    10 |00 |  01 |\n    10 |  01 |01001010/   00 |/  |01 \\_____ /0101000 |00 |__10/|\n    10 |  00 |00/    / |  10  00/ 00/    / |00    00 |00/   00/\n    00/   10/  0101000/    0010/   0010010/  0010100/ 1010100/\n                                                      00 |\n    Network Protocol Analysis Framework               00 |\n    created by Philipp Mieden, 2018                   00/\n    v0.5\n    \n    Homepage: https://netcap.io\n    GitHub: https://github.com/dreadl0ck/netcap"
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"netcap\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Audit Records Total",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nc_protocols_total)" }
   ]
  },
  {
   "title": "Audit Record Types",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nc_protocols_total) by(Protocol)",
     "legendFormat": "{{Protocol}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "nc_uptime", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 },
   "content": "\n# Summary\n\nA summary of the most relevant stats\n\n\n"
  },
  {
   "title": "Packets Processed",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nc_numpackets)" }
   ]
  },
  {
   "title": "Unknown Protocols",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nc_unknown_protocols_total)"
    }
   ]
  },
  {
   "title": "Decoding Errors",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nc_decoding_errors_total)" }
   ]
  },
  {
   "title": "Rate by Protocol",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nc_protocols_total{instance=~\"$instance\"}[$queryInterval])",
     "legendFormat": "{{Protocol}}"
    }
   ]
  },
  {
   "title": "Decoding Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(nc_decoding_errors_total{instance=~\"$instance\"}[$queryInterval])",
     "legendFormat": "{{Error}}"
    }
   ]
  },
  {
   "title": "Exporter Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "IPv4", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 45 },
   "content": "\n# Internet Protocol Version 4\n\nThe Internet Protocol (IP) is the principal communications protocol in the Internet protocol suite for relaying datagrams across network boundaries. Its routing function enables internetworking, and essentially establishes the Internet.\n\nIP has the task of delivering packets from the source host to the destination host solely based on the IP addresses in the packet headers. For this purpose, IP defines packet structures that encapsulate the data to be delivered. \n\nIt also defines addressing methods that are used to label the datagram with source and destination information.\n\n\n\n"
  },
  {
   "title": "Rate of Packet Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(nc_ipv4_size_sum[$queryInterval])"
    }
   ]
  },
  {
   "title": "Rate of Packet Payload Entropy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nc_ipv4_entropy_sum[$queryInterval]) / rate(nc_ipv4_entropy_count[$queryInterval])"
    }
   ]
  },
  {
   "title": "Sum of TTL values",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(nc_ipv4{}) by(TTL)", "legendFormat": "{{TTL}}" }
   ]
  },
  {
   "title": "SrcIP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(nc_ipv4) by(SrcIP)", "legendFormat": "{{SrcIP}}" }
   ]
  },
  {
   "title": "Flags",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(nc_ipv4) by(Flags)", "legendFormat": "{{Flags}}" }
   ]
  },
  {
   "title": "DstIP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(nc_ipv4) by(DstIP)", "legendFormat": "{{DstIP}}" }
   ]
  },
  {
   "title": "IPv6",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 46 },
     "content": "\n# Internet Protocol Version 6\n\nThe Internet Protocol (IP) is the principal communications protocol in the Internet protocol suite for relaying datagrams across network boundaries. Its routing function enables internetworking, and essentially establishes the Internet.\n\nIP has the task of delivering packets from the source host to the destination host solely based on the IP addresses in the packet headers. For this purpose, IP defines packet structures that encapsulate the data to be delivered. \n\nIt also defines addressing methods that are used to label the datagram with source and destination information.\n\n\n"
    },
    {
     "title": "Rate of Packet Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(nc_ipv6_size_count[$queryInterval])"
      }
     ]
    },
    {
     "title": "Rate of Packet Payload Entropy",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nc_ipv6_entropy_sum[$queryInterval]) / rate(nc_ipv6_entropy_count[$queryInterval])",
       "legendFormat": "IPv6 Entropy"
      }
     ]
    },
    {
     "title": "HopLimit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sum(nc_ipv6{}) by(HopLimit)", "legendFormat": "{{HopLimit}}" }
     ]
    },
    {
     "title": "SrcIP",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sum(nc_ipv6) by(SrcIP)", "legendFormat": "{{SrcIP}}" }
     ]
    },
    {
     "title": "IPv6 TrafficClass",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sum(nc_ipv6) by(TrafficClass)", "legendFormat": "{{TrafficClass}}" }
     ]
    },
    {
     "title": "IPv6 DstIP",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sum(nc_ipv6) by(DstIP)", "legendFormat": "{{DstIP}}" }
     ]
    },
    {
     "title": "NextHeader",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sum(nc_ipv6) by(NextHeader)", "legendFormat": "{{NextHeader}}" }
     ]
    },
    {
     "title": "IPv6 FlowLabel",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sum(nc_ipv6) by(FlowLabel)", "legendFormat": "{{FlowLabel}}" }
     ]
    }
   ]
  },
  { "title": "TCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 76 },
   "content": "\n# Transmission Control Protocol\n\nThe Transmission Control Protocol (TCP) is one of the main protocols of the Internet protocol suite. \nIt originated in the initial network implementation in which it complemented the Internet Protocol (IP). \nTherefore, the entire suite is commonly referred to as TCP/IP. \n\nTCP provides reliable, ordered, and error-checked delivery of a stream of octets (bytes) between applications running on hosts communicating via an IP network. Major internet applications such as the World Wide Web, email, remote administration, and file transfer rely on TCP. \n"
  },
  {
   "title": "Packets by SrcPort",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 80 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nc_tcp) by(SrcPort)", "legendFormat": "{{SrcPort}}" }
   ]
  },
  {
   "title": "Packets by DstPort",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 80 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nc_tcp) by(DstPort)", "legendFormat": "{{DstPort}}" }
   ]
  },
  {
   "title": "TCP Packets with URG Flag set",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 80 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nc_tcp) by(URG)", "legendFormat": "{{URG}}" }
   ]
  },
  {
   "title": "TCP Payload Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(nc_tcp_size_count[$queryInterval])",
     "legendFormat": "TCP Payload Entropy"
    }
   ]
  },
  {
   "title": "TCP Payload Entropy",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nc_tcp_entropy_sum[$queryInterval]) / rate(nc_tcp_entropy_count[$queryInterval])",
     "legendFormat": "TCP Payload Entropy"
    }
   ]
  },
  {
   "title": "Packets with ACK Flag set",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 98 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nc_tcp) by(ACK)", "legendFormat": "{{ACK}}" }
   ]
  },
  {
   "title": "Packets with RST Flag set",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 98 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nc_tcp) by(RST)", "legendFormat": "{{RST}}" }
   ]
  },
  {
   "title": "Packets with SYN Flag set",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 98 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nc_tcp) by(SYN)", "legendFormat": "{{SYN}}" }
   ]
  },
  { "title": "UDP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 108 },
   "content": "\n# User Datagram Protocol\n\nIn computer networking, the User Datagram Protocol (UDP) is one of the core members of the Internet protocol suite.\nThe protocol was designed by David P. Reed in 1980 and formally defined in RFC 768. \n\nWith UDP, computer applications can send messages, in this case referred to as datagrams, to other hosts on an Internet Protocol (IP) network.\nPrior communications are not required in order to set up communication channels or data paths.\n"
  },
  {
   "title": "UDP Packets Total",
   "type": "singlestat",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 112 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nc_udp)" }
   ]
  },
  {
   "title": "Packets by SrcPort",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 112 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nc_udp{instance=~\"$instance\"}) by(SrcPort)",
     "legendFormat": "{{SrcPort}}"
    }
   ]
  },
  {
   "title": "Packets by DstPort",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 112 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nc_udp{instance=~\"$instance\"}) by(DstPort)",
     "legendFormat": "{{DstPort}}"
    }
   ]
  },
  {
   "title": "UDP Packet Rate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nc_protocols_total{Protocol=\"UDP\"}[$queryInterval])"
    }
   ]
  },
  {
   "title": "Rate of Payload Entropy",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(nc_udp_entropy_count{instance=~\"$instance\"}[$queryInterval])"
    }
   ]
  },
  {
   "title": "Rate of Payload Size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 136 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(nc_udp_size_count{instance=~\"$instance\"}[$queryInterval])"
    }
   ]
  },
  { "title": "DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 146 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 147 },
   "content": "\n# Domain Name System\n\nThe Domain Name System (DNS) is a hierarchical and decentralized naming system for computers, services, or other resources connected to the Internet or a private network. \n\nIt associates various information with domain names assigned to each of the participating entities. \n\nMost prominently, it translates more readily memorized domain names to the numerical IP addresses needed for locating and identifying computer services and devices with the underlying network protocols. \n\nBy providing a worldwide, distributed directory service, the Domain Name System has been an essential component of the functionality of the Internet since 1985.\n\n\n"
  },
  {
   "title": "DNS Questions",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 153 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nc_dns) by(Questions)", "legendFormat": "{{Questions}}" }
   ]
  },
  {
   "title": "DNS QR",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 163 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nc_dns) by(QR)", "legendFormat": "{{QR}}" }
   ]
  },
  {
   "title": "DNS AA",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 163 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nc_dns) by(AA)", "legendFormat": "{{AA}}" }
   ]
  },
  {
   "title": "DNS QDCount",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 172 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nc_dns) by(QDCount)", "legendFormat": "{{QDCount}}" }
   ]
  },
  {
   "title": "DNS OpCode",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 172 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nc_dns) by(OpCode)", "legendFormat": "{{OpCode}}" }
   ]
  },
  {
   "title": "DNS Packet Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 181 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(nc_protocols_total{Protocol=\"DNS\"}[$queryInterval])",
     "legendFormat": "DNS"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 189 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 190 },
   "content": "\n# Hypertext Transfer Protocol\n\nThe Hypertext Transfer Protocol (HTTP) is an application protocol for distributed, collaborative, hypermedia information systems.\n\nHTTP is the foundation of data communication for the World Wide Web, where hypertext documents include hyperlinks to other resources that the user can easily access, for example by a mouse click or by tapping the screen in a web browser. \n\nHTTP was developed to facilitate hypertext and the World Wide Web.\n\n\n"
  },
  {
   "title": "Hosts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 195 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(nc_http{instance=~\"$instance\"}) by(Host)",
     "legendFormat": "{{Host}}"
    }
   ]
  },
  {
   "title": "User Agents",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 203 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nc_http) by(UserAgent)", "legendFormat": "{{UserAgent}}" }
   ]
  },
  {
   "title": "ReqContentLength",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 203 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nc_http) by(ReqContentLength)",
     "legendFormat": "{{ReqContentLength}}"
    }
   ]
  },
  {
   "title": "ReqContentEncoding",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 216 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nc_http) by(ReqContentEncoding)",
     "legendFormat": "{{ReqContentEncoding}}"
    }
   ]
  },
  {
   "title": "ReqContentType",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 216 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nc_http) by(ReqContentType)",
     "legendFormat": "{{ReqContentType}}"
    }
   ]
  },
  {
   "title": "Total HTTP requests to $host on $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 226 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nc_http{instance=~\"$instance\"}",
     "legendFormat": "{{Method}} {{URL}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 235 },
   "content": "\n# HTTP Responses\n\nThis section contains information about HTTP server replies\n\n\n"
  },
  {
   "title": "Response Status Codes",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 238 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nc_http) by(StatusCode)", "legendFormat": "{{StatusCode}}" }
   ]
  },
  {
   "title": "ResContentEncoding",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 238 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nc_http) by(ResContentEncoding)",
     "legendFormat": "{{ResContentEncoding}}"
    }
   ]
  },
  {
   "title": "Response Content Types",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 248 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nc_http) by(ResContentType)",
     "legendFormat": "{{ResContentType}}"
    }
   ]
  },
  {
   "title": "Server Names",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 248 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nc_http) by(ServerName)", "legendFormat": "{{ServerName}}" }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 258 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(nc_http) by (StatusCode)", "legendFormat": "{{StatusCode}}" }
   ]
  },
  {
   "title": "ResContentLength",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 266 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nc_http) by (ResContentLength)",
     "legendFormat": "{{ResContentLength}}"
    }
   ]
  },
  {
   "title": "TLS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 274 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 326 },
     "content": "\n# Transport Layer Security\n\nTransport Layer Security (TLS), and its now-deprecated predecessor, Secure Sockets Layer (SSL), are cryptographic protocols designed to provide communications security over a computer network.\n\nSeveral versions of the protocols find widespread use in applications such as web browsing, email, instant messaging, and voice over IP (VoIP). \n\nWebsites can use TLS to secure all communications between their servers and web browsers.\n\n\n"
    },
    {
     "title": "TLS Handshakes by SrcIP",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 331 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(nc_tlsclienthello) by(SrcIP)",
       "legendFormat": "{{SrcIP}}"
      }
     ]
    },
    {
     "title": "TLS Handshakes by DstIP",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 331 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(nc_tlsclienthello) by(DstIP)",
       "legendFormat": "{{DstIP}}"
      }
     ]
    },
    {
     "title": "TLS Handshakes by SrcPort",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 331 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(nc_tlsclienthello) by(SrcPort)",
       "legendFormat": "{{SrcPort}}"
      }
     ]
    },
    {
     "title": "TLS Handshakes by SrcMAC",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 339 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(nc_tlsclienthello) by(SrcMAC)",
       "legendFormat": "{{SrcMAC}}"
      }
     ]
    },
    {
     "title": "TLS Handshakes by DstMAC",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 339 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(nc_tlsclienthello) by(DstMAC)",
       "legendFormat": "{{DstMAC}}"
      }
     ]
    },
    {
     "title": "TLS Handshakes by DstPort",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 339 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(nc_tlsclienthello) by(DstPort)",
       "legendFormat": "{{DstPort}}"
      }
     ]
    },
    {
     "title": "Rate of TLS Handshakes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 347 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(increase(nc_tlsclienthello[$queryInterval])) by(SrcIP)",
       "legendFormat": "{{SrcIP}}"
      }
     ]
    },
    {
     "title": "Ja3 Fingerprints",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 356 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sum(nc_tlsclienthello) by(Ja3)", "legendFormat": "{{Ja3}}" }
     ]
    },
    {
     "title": "CipherSuiteLen",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 356 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(nc_tlsclienthello) by(CipherSuiteLen)",
       "legendFormat": "{{CipherSuiteLen}}"
      }
     ]
    },
    {
     "title": "ExtensionLen",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 364 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(nc_tlsclienthello) by(ExtensionLen)",
       "legendFormat": "{{ExtensionLen}}"
      }
     ]
    },
    {
     "title": "HandshakeLen",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 364 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(nc_tlsclienthello) by(HandshakeLen)",
       "legendFormat": "{{HandshakeLen}}"
      }
     ]
    },
    {
     "title": "SupportedGroups",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 372 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(nc_tlsclienthello) by(SupportedGroups)",
       "legendFormat": "{{SupportedGroups}}"
      }
     ]
    },
    {
     "title": "SupportedPoints",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 372 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(nc_tlsclienthello) by(SupportedPoints)",
       "legendFormat": "{{SupportedPoints}}"
      }
     ]
    },
    {
     "title": "OSCP",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 380 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(nc_tlsclienthello) by(OSCP)",
       "legendFormat": "{{OSCP}}"
      }
     ]
    },
    {
     "title": "HandshakeVersion",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 380 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(nc_tlsclienthello) by(HandshakeVersion)",
       "legendFormat": "{{HandshakeVersion}}"
      }
     ]
    }
   ]
  }
 ]
}